### ISSUE TITLE
Initial website checklist

### ISSUE THREAD

**Issue by jbunke** [jbunke/se#1]
* [x] API with table of contents sidebar
* [x] Home page as HTML with feature gifs
* [x] FAQ page
* [x] Demo page
* [x] Initial documentation merged into master and updated submodule
* [x] Change API links in documentation and vice versa to relative site links - it's okay that these links will break on GitHub
  * [x] Links in API
  * [x] Links in docs
* [x] Add "Edit this page" to API and documentation pages with Liquid in respective layout files
  * [x] API
  * [x] Documentation
